// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfehAvDRIstKpnhAa5_8Z4uPeexX9l1SQ',
    appId: '1:543995537068:web:6d76896697452f0704a109',
    messagingSenderId: '543995537068',
    projectId: 'campuscare-e812f',
    authDomain: 'campuscare-e812f.firebaseapp.com',
    storageBucket: 'campuscare-e812f.firebasestorage.app',
    measurementId: 'G-72X0JMGC77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUXKdodkBcvDmFycVCnvb3wFf6LQ1GPs',
    appId: '1:543995537068:android:94bf8c8722a0d3ae04a109',
    messagingSenderId: '543995537068',
    projectId: 'campuscare-e812f',
    storageBucket: 'campuscare-e812f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfaS9GzWmteMSL4Lk48ctV9mR1VUsclO4',
    appId: '1:543995537068:ios:4df67a1846c557ee04a109',
    messagingSenderId: '543995537068',
    projectId: 'campuscare-e812f',
    storageBucket: 'campuscare-e812f.firebasestorage.app',
    iosBundleId: 'com.example.customerCareWebapp',
  );
}
